name: "update-cri-dockerd-version"
on:
  workflow_dispatch:
  schedule:
    # every Monday at around 3 am pacific/10 am UTC
    - cron: "0 10 * * 1"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.21.1'
permissions:
  contents: read

jobs:
  bump-cri-dockerd-version:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
        with:
          go-version: ${{env.GO_VERSION}}
          cache-dependency-path: ./go.sum
      - name: Bump cri-dockerd version
        id: bumpCriDockerd
        run: |
          echo "OLD_VERSION=$(DEP=cri-dockerd make get-dependency-version)" >> $GITHUB_OUTPUT
          make update-cri-dockerd-version
          echo "NEW_VERSION=$(DEP=cri-dockerd make get-dependency-version)" >> $GITHUB_OUTPUT
          # The following is to support multiline with GITHUB_OUTPUT, see https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
          echo "changes<<EOF" >> $GITHUB_OUTPUT
          echo "$(git status --porcelain)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Create PR
        id: createPR
        if: ${{ steps.bumpCriDockerd.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: 'Kicbase/ISO: Update cri-dockerd from ${{ steps.bumpCriDockerd.outputs.OLD_VERSION }} to ${{ steps.bumpCriDockerd.outputs.NEW_VERSION }}'
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: auto_bump_cri_dockerd_version
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: 'Kicbase/ISO: Update cri-dockerd from ${{ steps.bumpCriDockerd.outputs.OLD_VERSION }} to ${{ steps.bumpCriDockerd.outputs.NEW_VERSION }}'
          body: |
            The cri-dockerd project released a [new version](https://github.com/Mirantis/cri-dockerd)

            This PR was auto-generated by `make update-cri-dockerd-version` using [update-cri-dockerd-version.yml](https://github.com/kubernetes/minikube/tree/master/.github/workflows/update-cri-dockerd-version.yml) CI Workflow.

            A minikube maintainer needs to checkout this PR, run `make build-and-upload-cri-dockerd-binaries`, and then comment `ok-to-build-image`.
      - uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410
        if: ${{ steps.bumpCriDockerd.outputs.changes != '' }}
        with:
          github-token: ${{ secrets.MINIKUBE_BOT_PAT }}
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ steps.createPR.outputs.pull-request-number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'ok-to-build-iso'
            })
