name: "update-kubernetes-versions-list"
on:
  workflow_dispatch:
  schedule:
    # every Monday at around midnight pacific/7 am UTC
    - cron: "0 6 * * 1"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.21.1'
permissions:
  contents: read

jobs:
  update-kubernetes-versions-list:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
        with:
          go-version: ${{env.GO_VERSION}}
          cache-dependency-path: ./go.sum
      - name: Bump Kubernetes versions list
        id: bumpKubernetesVersionsList
        run: |
          make update-kubernetes-versions-list
          c=$(git status --porcelain)
          # The following is to support multiline with GITHUB_OUTPUT, see https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
          echo "changes<<EOF" >> $GITHUB_OUTPUT
          echo "$c" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Create PR
        if: ${{ steps.bumpKubernetesVersionsList.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: update Kubernetes versions list
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: auto_update_kubernetes_versions_list
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: 'Update Kubernetes versions list'
          body: |
            This PR was auto-generated by `make update-kubernetes-versions-list` using [update-kubernetes-versions-list.yml](https://github.com/kubernetes/minikube/tree/master/.github/workflows/update-kubernetes-versions-list.yml) CI Workflow.
